export const PET_PHRASES: Record<string, string[]> = {
  dog: [
    'Woof! 🐕', 'Bark bark!', 'Ready to play?', 'Pet me!', 'Best friends forever!',
    'I\'m a good boy!', 'Tail wag!', 'Ruff ruff!', 'Can we go for a walk?', 'You\'re awesome!',
    'Paws up!', 'Fetch?', 'I love you!', 'Let\'s play fetch!', 'Wanna snuggle?',
    'Happy happy!', 'Bork bork!', 'Good human!', 'More treats?', 'Best day ever!',
    'Puppy power!', 'Lick lick!', 'Tail spin!', 'Doggo approved!', 'Zoomies time!',
    'Playtime!', 'Chase me!', 'So loyal!', 'Pawsome!', 'Doggo dreams!',
    'Stick throw!', 'Belly rubs!', 'Whimper whimper!', 'Dig dig dig!', 'Arf!',
    'Bark at birds!', 'Stick-to-me!', 'Slobber!', 'Bounce bounce!', 'Spin spin!',
    'Howl howl!', 'Good doggo!', 'Best bud!', 'Always happy!', 'Never sad!',
    'Treats please!', 'Water bowl!', 'Nap time!', 'Stretch stretch!', 'Cuddle buddy!',
    'Forever loyal!', 'Park time!', 'Squirrel!', 'Mailman!', 'Tail chase!',
    'Love you loads!', 'Bark once!', 'Wag it!', 'Pant pant!', 'Drool!',
    'Beg beg!', 'Sit sit!', 'Stay stay!', 'Shake paw!', 'Roll over!',
    'Play dead!', 'Get it!', 'Drop it!', 'Leave it!', 'Come here!'
  ],
  fox: [
    'What\'s up? 🦊', 'Ring-ding-ding!', 'Sly fox!', 'Looking good!', 'Sneaky sneaky',
    'Clever me!', 'Foxes rule!', 'Elegant and smart', 'I\'m adorable', 'Watch me',
    'Giddy up!', 'So fluffy!', 'Orange you glad?', 'Tail swish', 'Mysterious',
    'Playful mood', 'Quick thinking', 'Cunning plan', 'Bushy tail!', 'Pounce!',
    'Fox fire!', 'Sly moves!', 'Quick dash!', 'Sneak sneak!', 'Ears up!',
    'Fluffy fur!', 'Golden beauty!', 'Cunning fox!', 'Night hunter!', 'Swift feet!',
    'Witty brain!', 'Silent paws!', 'Amber eyes!', 'Forest dweller!', 'Wild spirit!',
    'Pounce pounce!', 'Chase tail!', 'Dig hole!', 'Hide treasure!', 'Yodel!',
    'So smart!', 'Tricky fox!', 'Playful tricks!', 'Mischief maker!', 'Sly grin!',
    'Fox nap!', 'Dream hunt!', 'Stretch out!', 'Groom fur!', 'Shake tail!',
    'So graceful!', 'Elegant move!', 'Swift run!', 'Quiet stalker!', 'Perfect jump!',
    'Fox facts!', 'Stay clever!', 'Be sly!', 'Stay wild!', 'Be free!',
    'Fox love!', 'Fox life!', 'Orange beauty!', 'Unique charm!', 'Unforgettable!'
  ],
  chicken: [
    'Bawk bawk! 🐔', 'Cluck cluck!', 'Eggs!', 'Who\'s that?', 'Pecking time!',
    'I\'m fabulous!', 'Cluck-a-doodle!', 'Scratch scratch', 'Shiny feathers', 'Strut strut',
    'Look at me!', 'Roosting', 'Corn tastes good', 'Pretty bird!', 'Fluff fluff',
    'Waddle waddle', 'I\'m hungry!', 'Farmyard life', 'Bawk bawk bawk!', 'So fancy!',
    'Peck peck!', 'Feather ruffle!', 'Cockle doodle!', 'Morning alarm!', 'Nest time!',
    'Sunny spot!', 'Dust bath!', 'Grain pecking!', 'Cluck cluck cluck!', 'Coop queen!',
    'Bright eyes!', 'Red comb!', 'Golden feathers!', 'Farm pride!', 'Egg layer!',
    'Barnyard boss!', 'Feather fluff!', 'Tiny feet!', 'Loud voice!', 'Happy clucks!',
    'Morning call!', 'Noon rest!', 'Evening roost!', 'Sleep time!', 'Dream chicken!',
    'No worries!', 'Simple life!', 'Farm fresh!', 'Natural beauty!', 'Pure joy!',
    'Bawk bawk bawk bawk!', 'So social!', 'Flock friend!', 'Stick together!', 'Pecking party!',
    'Grit eating!', 'Worm finding!', 'Bug hunting!', 'Scratch scratchin!', 'Mud bath!',
    'Feather puff!', 'Tail waggle!', 'Head bob!', 'Wing flap!', 'Proud strut!'
  ],
  deno: [
    'Rawr! 🦕', 'Dinosaur power!', 'Stomp stomp!', 'I\'m extinct cool', 'Prehistoric vibes',
    'Dino mite!', 'Tail wag dino', 'Roaaaaarrr!', 'Green and mean', 'Ancient awesome',
    'Dino strength', 'Meteor? Nah!', 'Thunderlizard!', 'Rock on!', 'Dino claws',
    'Long neck life', 'Jungle king', 'Dino swag', 'Evolution rules', 'Reptile squad',
    'Dino stomp!', 'Big feet!', 'Strong tail!', 'Huge body!', 'Ancient beast!',
    'Fossil cool!', 'Time travel!', 'Era king!', 'Prehistoric party!', 'Dino dance!',
    'Roar roar!', 'Stomp stomp stomp!', 'Tail swish!', 'Head hold high!', 'Proud dino!',
    'Green scales!', 'Powerful legs!', 'Long tail!', 'Big teeth!', 'Cool freak!',
    'Dino fact!', 'Dino life!', 'Dino love!', 'Stay strong!', 'Be mighty!',
    'Jungle roam!', 'Forest stomp!', 'Land ruler!', 'Apex predator!', 'King dino!',
    'Dino rest!', 'Dino nap!', 'Dino dream!', 'Dino stretch!', 'Dino wake!',
    'Tail power!', 'Claw sharp!', 'Bite strong!', 'Run fast!', 'Jump high!',
    'Dino cool!', 'Dino rare!', 'Dino unique!', 'Dino special!', 'Dino awesome!'
  ],
  panda: [
    'Munch munch! 🐼', 'Bamboo time!', 'So cuddly!', 'Relaxed vibes', 'Chill panda',
    'Bamboo is life', 'Hug me!', 'Lazy mode', 'Peaceful soul', 'Adorable fluffball',
    'Nom nom nom', 'Zen master', 'Black and white', 'Rolling around', 'Sleepy panda',
    'Gentle giant', 'Nature lover', 'Simple life', 'Love and peace', 'Bamboo forever',
    'Bamboo feast!', 'Munch munch munch!', 'Yum yum!', 'Happy belly!', 'Peaceful eater!',
    'Slow motion!', 'No rush!', 'Relax time!', 'Chill zone!', 'Panda zen!',
    'Soft fur!', 'Round shape!', 'Cute face!', 'Big eyes!', 'Tiny ears!',
    'Bamboo stalk!', 'Chewing sounds!', 'Content panda!', 'Full stomach!', 'Sleepy now!',
    'Nap time!', 'Dream bamboo!', 'Stretch out!', 'Yawn yawn!', 'Eyes close!',
    'Wake up!', 'Time to eat!', 'Bamboo calls!', 'Nature walks!', 'Forest home!',
    'Panda love!', 'Panda life!', 'Panda joy!', 'Panda peace!', 'Panda forever!',
    'So gentle!', 'Not aggressive!', 'Kind nature!', 'Harmless friend!', 'Sweet soul!',
    'Black patches!', 'White fur!', 'Unique pattern!', 'Beautiful design!', 'Perfect panda!'
  ],
  horse: [
    'Neigh! 🐴', 'Gallop time!', 'Strong horse', 'Majestic vibes', 'Speedy!',
    'Run wild!', 'Mane goals', 'Hoof stomp', 'Stallion life', 'Graceful steed',
    'Fast as wind', 'Noble beast', 'Saddle up!', 'Meadow time', 'Powerful legs',
    'Gentle giant', 'Race you!', 'Hay is great', 'Beautiful coat', 'Horsepower!',
    'Trot trot!', 'Canter canter!', 'Gallop go!', 'Jump jump!', 'Run fast!',
    'Hay munch!', 'Water drink!', 'Grass graze!', 'Stable rest!', 'Pasture life!',
    'Shiny coat!', 'Silky mane!', 'Long tail!', 'Strong back!', 'Proud stance!',
    'Majestic beauty!', 'Powerful stride!', 'Noble head!', 'Loyal friend!', 'Trusted steed!',
    'Neigh neigh!', 'Whinny call!', 'Snort sound!', 'Hoof beat!', 'Prance prance!',
    'Morning ride!', 'Afternoon run!', 'Evening rest!', 'Night sleep!', 'Dream gallop!',
    'So strong!', 'So fast!', 'So beautiful!', 'So loyal!', 'So smart!',
    'Horse love!', 'Horse life!', 'Horse freedom!', 'Horse power!', 'Horse glory!',
    'Sunset ride!', 'Morning gallop!', 'Field run!', 'Trail adventure!', 'Perfect companion!'
  ],
  monkey: [
    'Ooh ooh! 🐒', 'Monkey see!', 'Swing swing!', 'Mischief mode', 'Banana time!',
    'Go bananas!', 'Climbing high', 'Monkey business', 'Playful primate', 'Cheeky chimp',
    'Jump around!', 'Shriek shriek!', 'Acrobat monkey', 'Silly monkey', 'Jungle vibes',
    'I\'m clever!', 'Swinging free', 'Tree time!', 'Social butterfly', 'Wild and free',
    'Banana peel!', 'Munch crunch!', 'Yum yum!', 'More fruit!', 'Peel peel!',
    'Swing swing swing!', 'Higher higher!', 'Zoom zoom!', 'Tree jump!', 'Branch grab!',
    'Acrobat flip!', 'Handstand!', 'Somersault!', 'Twist twist!', 'Bounce bounce!',
    'Ooh ooh ooh!', 'Shriek shriek shriek!', 'Chatter chatter!', 'Noise maker!', 'Loud voice!',
    'Monkey hug!', 'Group groom!', 'Social time!', 'Stick together!', 'Family bonds!',
    'Tree home!', 'Jungle life!', 'Branch bed!', 'Leaf shelter!', 'Safe space!',
    'Curious mind!', 'Smart tricks!', 'Learning fast!', 'Problem solver!', 'Tool user!',
    'Play fight!', 'Tail grab!', 'Wrestle wrestle!', 'Tag tag!', 'Chase game!',
    'Monkey love!', 'Monkey joy!', 'Monkey freedom!', 'Monkey spirit!', 'Monkey forever!'
  ],
  crab: [
    'Pinch pinch! 🦀', 'Snap snap!', 'Sideways shuffle!', 'Claw power!', 'Beach vibes!',
    'Bubble bubble!', 'Shell yeah!', 'Crabby mood!', 'Sandy claws!', 'Tide pool life!',
    'Scuttle scuttle!', 'Click clack!', 'Snip snip!', 'Crab walk!', 'Ocean breeze!',
    'Under the sea!', 'Coral explorer!', 'Rock hider!', 'Wave rider!', 'Salt life!',
    'Pinch power!', 'Double claws!', 'Guard mode!', 'Don\'t touch!', 'I\'ll pinch you!',
    'Sideways is best!', 'Who needs forward?', 'Left right left!', 'Shuffle master!', 'Smooth moves!',
    'Dig dig dig!', 'Sand castle!', 'Burrow time!', 'Hide away!', 'Peek-a-boo!',
    'Sun bathing!', 'Warm rocks!', 'Shell spa!', 'Chill mode!', 'Relaxing!',
    'Crab dance!', 'Claw wave!', 'Snappy steps!', 'Groove time!', 'Party crab!',
    'Tough shell!', 'Armor up!', 'Can\'t crack me!', 'Shell strong!', 'Built tough!',
    'Seaweed snack!', 'Nom nom!', 'Tasty algae!', 'Feast time!', 'Yummy!',
    'Crab friends!', 'Colony life!', 'Stick together!', 'Crab squad!', 'Team pinch!',
    'Moon watching!', 'Tide coming!', 'Stars above!', 'Night swim!', 'Midnight crab!',
    'Crab life!', 'Born crabby!', 'Claw-some!', 'Shell-ebrate!', 'Crab forever!'
  ],
  clippy: [
    'Need help? 📎', 'It looks like you\'re writing!', 'I\'m here to help!', 'Click me!', 'Hi there!',
    'Looks like a letter!', 'Want a tip?', 'I see you typing!', 'Assistant mode!', 'At your service!',
    'Remember me?', 'I\'m back!', 'Miss me?', 'Classic vibes!', 'Retro helper!',
    'Let me help!', 'Pro tip incoming!', 'Did you know?', 'Fun fact!', 'Helpful hint!',
    'You\'re doing great!', 'Keep going!', 'Almost there!', 'Nice work!', 'Looking good!',
    'Paperclip power!', 'Bend and flex!', 'Shiny metal!', 'Clip clip!', 'Hold it together!',
    'Office buddy!', 'Desk friend!', 'Work companion!', 'Meeting time?', 'Email check!',
    'Save your work!', 'Don\'t forget!', 'Backup time!', 'Ctrl+S!', 'Save often!',
    'Spell check?', 'Grammar tip!', 'Format that!', 'Bold move!', 'Italic mood!',
    'Copy paste!', 'Undo undo!', 'Redo that!', 'Select all!', 'Find replace!',
    'Wiggle wiggle!', 'Bounce bounce!', 'Lean left!', 'Lean right!', 'Spin spin!',
    'Tab tab tab!', 'New document!', 'Print preview!', 'Page setup!', 'Margin check!',
    'I\'m iconic!', 'Living legend!', 'Never forgotten!', 'Nostalgia trip!', 'Y2K vibes!',
    'Clip forever!', 'Best assistant!', 'Always watching!', 'Always helping!', 'Clippy lives!'
  ],
  cockatiel: [
    'Tweet tweet! 🦜', 'Chirp chirp!', 'Pretty bird!', 'Whistle whistle!', 'Head scratches!',
    'Crest up!', 'Crest down!', 'Fluffy cheeks!', 'Orange cheeks!', 'So soft!',
    'Sing along!', 'La la la!', 'Melody time!', 'Whistling tune!', 'Concert mode!',
    'Seed please!', 'Millet time!', 'Crunch crunch!', 'Snack attack!', 'Yummy seeds!',
    'Preen preen!', 'Feather check!', 'Looking good!', 'Groom time!', 'Shiny feathers!',
    'Step up!', 'Good bird!', 'Clever tiel!', 'Smart birdie!', 'Learning tricks!',
    'Head bob!', 'Dance dance!', 'Beak tap!', 'Wing stretch!', 'Tail wag!',
    'Peek-a-boo!', 'Hide and seek!', 'Under wing!', 'Snuggle time!', 'Cozy bird!',
    'Flock call!', 'Where are you?', 'Come here!', 'Follow me!', 'Stick together!',
    'Nap time!', 'One foot up!', 'Sleepy tiel!', 'Tuck beak!', 'Zzz zzz!',
    'Mirror mirror!', 'Who\'s that?', 'Pretty me!', 'Reflection!', 'So handsome!',
    'Fly fly!', 'Wing flap!', 'Soar high!', 'Landing!', 'Perch time!',
    'Tiel love!', 'Birb life!', 'Feathered friend!', 'Cockatiel crew!', 'Tiel forever!'
  ],
  mod: [
    'Beep boop! 👾', 'Modding time!', 'Pixel power!', 'Glitch mode!', 'System hack!',
    'Override!', 'Access granted!', 'Code inject!', 'Patch applied!', 'Debug mode!',
    'Purple haze!', 'Neon glow!', 'Digital vibes!', 'Cyber punk!', 'Matrix style!',
    'Mod squad!', 'Power up!', 'Level up!', 'XP gained!', 'Boss fight!',
    'Binary beats!', '01101001!', 'Data stream!', 'Byte me!', 'Bit flip!',
    'Spawn point!', 'Respawn!', 'Save state!', 'Load game!', 'Continue?',
    'Pixel perfect!', 'Render done!', 'Frame rate!', 'No lag!', 'Smooth run!',
    'Easter egg!', 'Secret found!', 'Hidden path!', 'Bonus stage!', 'Warp zone!',
    'Alt tab!', 'Ctrl alt!', 'Shift key!', 'Escape!', 'Enter!',
    'Firewall up!', 'Encrypted!', 'Secure mode!', 'Shield on!', 'Protected!',
    'Mod life!', 'Custom build!', 'Overclock!', 'Turbo mode!', 'Max power!',
    'Compile done!', 'No errors!', 'Tests pass!', 'Ship it!', 'Deploy!',
    'Mod forever!', 'Pixel soul!', 'Digital dream!', 'Cyber friend!', 'Glitch art!'
  ],
  morph: [
    'Wooooo! 👻', 'Shape shift!', 'Transform!', 'Morph time!', 'New form!',
    'Boo!', 'Spooky!', 'Ghost mode!', 'Invisible!', 'Fade away!',
    'Ectoplasm!', 'Floating!', 'Through walls!', 'Haunting!', 'Creepy cool!',
    'Who am I?', 'What am I?', 'Mystery!', 'Unknown form!', 'Shape unknown!',
    'Purple mist!', 'Smoke puff!', 'Vapor trail!', 'Fog cloud!', 'Misty!',
    'Morph attack!', 'Form change!', 'Shift shape!', 'Evolve!', 'Mutate!',
    'Phantom!', 'Specter!', 'Wraith!', 'Shade!', 'Spirit!',
    'Dissolve!', 'Reform!', 'Reassemble!', 'Reconstruct!', 'Rebuild!',
    'Copy that!', 'Mirror form!', 'Clone!', 'Duplicate!', 'Double!',
    'Amorphous!', 'Fluid!', 'Liquid!', 'Flexible!', 'Stretchy!',
    'Surprise!', 'Gotcha!', 'Now you see me!', 'Poof!', 'Ta-da!',
    'Phase shift!', 'Dimension hop!', 'Warp!', 'Teleport!', 'Blink!',
    'Morph life!', 'Shape soul!', 'Form free!', 'Ever changing!', 'Morph forever!'
  ],
  rat: [
    'Squeak squeak! 🐀', 'Cheese please!', 'Nibble nibble!', 'Tiny paws!', 'Whiskers twitch!',
    'Scurry scurry!', 'Quick dash!', 'Sneaky rat!', 'Tunnel time!', 'Hide away!',
    'Smart rat!', 'Clever brain!', 'Maze master!', 'Problem solver!', 'Quick learner!',
    'Cheese hunt!', 'Sniff sniff!', 'Found it!', 'Yummy!', 'More cheese!',
    'Tail swish!', 'Nose wiggle!', 'Ear perk!', 'Eyes bright!', 'Alert mode!',
    'Nest building!', 'Cozy corner!', 'Warm spot!', 'Safe place!', 'Home sweet home!',
    'Night runner!', 'Dark explorer!', 'Shadow walker!', 'Stealth mode!', 'Silent paws!',
    'Rat pack!', 'Gang gang!', 'Squad goals!', 'Stick together!', 'Family first!',
    'Chew chew!', 'Gnaw gnaw!', 'Crunch time!', 'Munch munch!', 'Snack attack!',
    'Curious rat!', 'What\'s that?', 'Let me see!', 'Investigating!', 'Discovery!',
    'Acrobat rat!', 'Climb climb!', 'Balance!', 'Tight rope!', 'Parkour!',
    'Wash face!', 'Groom time!', 'Clean paws!', 'Tidy rat!', 'Fresh fur!',
    'Rat life!', 'Street smart!', 'Survivor!', 'Adaptable!', 'Rat forever!'
  ],
  rocky: [
    'Rock solid! 🪨', 'Standing strong!', 'Unmovable!', 'Hard as rock!', 'Stone cold!',
    'Boulder time!', 'Heavy weight!', 'Grounded!', 'Steady!', 'Firm!',
    'Rock and roll!', 'Rolling stone!', 'Tumble!', 'Avalanche!', 'Landslide!',
    'Mineral rich!', 'Crystal core!', 'Gem inside!', 'Shiny facet!', 'Sparkle!',
    'Mountain born!', 'Peak climber!', 'Summit!', 'High ground!', 'Top rock!',
    'Erosion proof!', 'Weather tough!', 'Rain? Whatever!', 'Wind? Nothing!', 'Storm? Easy!',
    'Fossil friend!', 'Ancient one!', 'Time keeper!', 'Old soul!', 'Wise stone!',
    'Pebble pal!', 'Little rock!', 'Smooth stone!', 'River rock!', 'Beach pebble!',
    'Crack? Never!', 'Chip proof!', 'Dent free!', 'Scratch resistant!', 'Indestructible!',
    'Gravity lover!', 'Down to earth!', 'Grounding!', 'Centered!', 'Balanced!',
    'Rock garden!', 'Zen stone!', 'Peace rock!', 'Calm boulder!', 'Meditation!',
    'Tectonic!', 'Plate shift!', 'Quake!', 'Rumble!', 'Earth power!',
    'Rock life!', 'Stone spirit!', 'Mineral soul!', 'Geo friend!', 'Rocky forever!'
  ],
  'rubber-duck': [
    'Quack quack! 🦆', 'Rubber ducky!', 'Bath time!', 'Squeak squeak!', 'Float float!',
    'Splish splash!', 'Bubble buddy!', 'Soap suds!', 'Tub friend!', 'Water fun!',
    'Debug duck!', 'Tell me the bug!', 'Explain your code!', 'Talk to me!', 'I\'m listening!',
    'Yellow fellow!', 'Bright and shiny!', 'Sunny duck!', 'Golden glow!', 'Lemon drop!',
    'Squeezy!', 'Squishy!', 'Soft touch!', 'Bouncy!', 'Springy!',
    'Duck duck!', 'Goose!', 'Waddle waddle!', 'Paddle paddle!', 'Swim swim!',
    'Quack attack!', 'Duck charge!', 'Bill bump!', 'Wing slap!', 'Tail shake!',
    'Pool party!', 'Splash zone!', 'Dive in!', 'Cannonball!', 'Making waves!',
    'Rubber soul!', 'Plastic fantastic!', 'Squeaky clean!', 'Fresh duck!', 'Mint condition!',
    'Duck army!', 'Quack squad!', 'Flock up!', 'Duck formation!', 'V shape!',
    'Rain dance!', 'Puddle jump!', 'Drip drop!', 'Wet feet!', 'Umbrella duck!',
    'Classic duck!', 'Iconic!', 'Timeless!', 'Original!', 'The OG!',
    'Duck life!', 'Quack soul!', 'Float free!', 'Rubber dream!', 'Duck forever!'
  ],
  skeleton: [
    'Rattle rattle! 💀', 'Bone shaker!', 'Spooky scary!', 'No body!', 'Just bones!',
    'Calcium power!', 'Strong bones!', 'Milk drinker!', 'Bone density!', 'Skeletal!',
    'Skull grin!', 'Jaw drop!', 'Eye socket!', 'Hollow head!', 'Brain free!',
    'Rib cage!', 'Spine tingler!', 'Backbone!', 'Femur flex!', 'Tibia tap!',
    'Bone dance!', 'Skeleton jig!', 'Rattling rhythm!', 'Click clack!', 'Boney boogie!',
    'X-ray vision!', 'See through!', 'Transparent!', 'Nothing to hide!', 'Open book!',
    'Halloween!', 'Trick or treat!', 'Boo!', 'Frightful!', 'Ghoulish!',
    'Doot doot!', 'Trumpet skull!', 'Horn bones!', 'Toot toot!', 'Spooky music!',
    'Grave escape!', 'Risen!', 'Undead!', 'Back again!', 'Never rest!',
    'Funny bone!', 'Humerus!', 'Knee slapper!', 'Skull joke!', 'Dead funny!',
    'Bone collector!', 'Skeleton key!', 'Closet free!', 'Out and about!', 'Living large!',
    'Marrow deep!', 'Core strong!', 'Inner strength!', 'Foundation!', 'Structure!',
    'Bone life!', 'Skeletal soul!', 'Rattle free!', 'Calcium dream!', 'Bones forever!'
  ],
  snail: [
    'Slow and steady! 🐌', 'Shell home!', 'Slime trail!', 'No rush!', 'Taking my time!',
    'Snail mail!', 'Special delivery!', 'Slow post!', 'Letter carrier!', 'Patience!',
    'Shell shock!', 'Curl up!', 'Safe inside!', 'Cozy shell!', 'Home sweet home!',
    'Leaf munch!', 'Garden friend!', 'Dew drop!', 'Morning mist!', 'Fresh greens!',
    'Trail blazer!', 'Path maker!', 'Shiny path!', 'Follow me!', 'This way!',
    'Rain lover!', 'Wet weather!', 'Puddle pal!', 'Moist mode!', 'Drizzle dance!',
    'Antenna wave!', 'Feeler check!', 'Eye stalk!', 'Look around!', 'Sensing!',
    'Spiral shell!', 'Golden ratio!', 'Perfect curve!', 'Math snail!', 'Fibonacci!',
    'Slow race!', 'Tortoise rival!', 'Steady pace!', 'Marathon!', 'Endurance!',
    'Mucus power!', 'Slick moves!', 'Smooth glide!', 'Friction free!', 'Sliding!',
    'Night owl snail!', 'Moon gazer!', 'Star slider!', 'Nocturnal!', 'Dark traveler!',
    'Hibernate!', 'Sleep mode!', 'Shell nap!', 'Dormant!', 'Estivate!',
    'Snail life!', 'Shell soul!', 'Slow spirit!', 'Gentle glide!', 'Snail forever!'
  ],
  snake: [
    'Hisss! 🐍', 'Ssslither!', 'Sssneaky!', 'Forked tongue!', 'Ssscales!',
    'Coil up!', 'Ssspiral!', 'Tight squeeze!', 'Constrict!', 'Wrap around!',
    'Sssmooth!', 'Sssleek!', 'Shiny scales!', 'Green machine!', 'Emerald beauty!',
    'Bask bask!', 'Sun spot!', 'Warm rock!', 'Heat seeker!', 'Cold blooded!',
    'Sssstrike!', 'Quick bite!', 'Fang flash!', 'Venom? Nah!', 'Friendly snake!',
    'Shed skin!', 'New look!', 'Fresh scales!', 'Makeover!', 'Rebirth!',
    'Tongue flick!', 'Taste air!', 'Sssmell that?', 'Detecting!', 'Ssscanning!',
    'Ground slide!', 'No legs? No problem!', 'Belly crawl!', 'Ssslide!', 'Glide!',
    'Tree climb!', 'Branch wrap!', 'High up!', 'Canopy life!', 'Hanging out!',
    'Egg guard!', 'Protect!', 'Watch over!', 'Careful!', 'Safe nest!',
    'Hypno eyes!', 'Mesmerize!', 'Ssspellbound!', 'Look into my eyes!', 'Charmer!',
    'Ancient one!', 'Wise serpent!', 'Old soul!', 'Knowledge!', 'Ssssage!',
    'Snake life!', 'Serpent soul!', 'Sssscale spirit!', 'Slither free!', 'Snake forever!'
  ],
  turtle: [
    'Slow ride! 🐢', 'Shell power!', 'Turtle time!', 'No hurry!', 'Steady wins!',
    'Shell hide!', 'Tuck in!', 'Safe inside!', 'Armor up!', 'Protected!',
    'Beach bound!', 'Ocean call!', 'Wave rider!', 'Sea turtle!', 'Deep dive!',
    'Ancient wisdom!', 'Old timer!', 'Centuries old!', 'Wise one!', 'Elder turtle!',
    'Sun bask!', 'Warm shell!', 'Log sit!', 'Lazy day!', 'Chill mode!',
    'Lettuce munch!', 'Veggie time!', 'Green feast!', 'Nom nom!', 'Salad bar!',
    'Paddle paddle!', 'Swim swim!', 'Flipper power!', 'Current ride!', 'Flow!',
    'Snap snap!', 'Strong jaw!', 'Bite force!', 'Careful!', 'Respect!',
    'Egg laying!', 'Sandy nest!', 'Moon night!', 'Baby turtles!', 'Tiny shells!',
    'Shell pattern!', 'Hexagons!', 'Nature art!', 'Beautiful!', 'Unique design!',
    'Retract!', 'Head in!', 'Legs in!', 'Full hide!', 'Box turtle!',
    'Migration!', 'Long journey!', 'Ocean cross!', 'Navigator!', 'Star guide!',
    'Turtle life!', 'Shell soul!', 'Slow spirit!', 'Patient heart!', 'Turtle forever!'
  ],
  vampire: [
    'Bleh bleh! 🧛', 'I vant blood!', 'Fangs out!', 'Bite bite!', 'Thirsty!',
    'Night walker!', 'Moonlight!', 'Darkness!', 'Shadow!', 'Nocturnal!',
    'Cape swirl!', 'Dramatic!', 'Elegant!', 'Classy!', 'Sophisticated!',
    'Immortal!', 'Forever young!', 'Eternal!', 'Ageless!', 'Undying!',
    'Coffin nap!', 'Upside down!', 'Bat mode!', 'Transform!', 'Shape shift!',
    'Garlic? No!', 'Sunlight? Ouch!', 'Mirror? None!', 'Cross? Yikes!', 'Stakes? Run!',
    'Castle life!', 'Transylvania!', 'Gothic vibes!', 'Dark tower!', 'Spooky manor!',
    'Hypnotize!', 'Look deep!', 'Under my spell!', 'Obey!', 'Mesmerize!',
    'Bat swarm!', 'Wings spread!', 'Fly fly!', 'Soar!', 'Night flight!',
    'Blood bank!', 'Donation?', 'Type O!', 'Red juice!', 'Crimson!',
    'Count me in!', 'One! Two! Three!', 'Ah ah ah!', 'Counting!', 'Numbers!',
    'Pale face!', 'Cold touch!', 'No pulse!', 'Ghostly!', 'Ethereal!',
    'Vampire life!', 'Fang soul!', 'Dark dream!', 'Eternal night!', 'Vampire forever!'
  ],
  zappy: [
    'Zap zap! ⚡', 'Electric!', 'Shock wave!', 'Thunder bolt!', 'Charged up!',
    'Bzzzzt!', 'Spark spark!', 'Lightning!', 'Flash!', 'Bright light!',
    'High voltage!', 'Power surge!', 'Overload!', 'Maximum!', 'Full charge!',
    'Static cling!', 'Hair raise!', 'Tingle!', 'Fuzzy!', 'Prickle!',
    'Battery full!', 'Energized!', 'Wired!', 'Amped up!', 'Supercharged!',
    'Bolt strike!', 'Ground hit!', 'Thunder clap!', 'Storm power!', 'Cloud burst!',
    'Neon glow!', 'Yellow flash!', 'Bright spark!', 'Light show!', 'Fireworks!',
    'Circuit board!', 'Watt\'s up!', 'Ohm my!', 'Current flow!', 'Resistance!',
    'Speed of light!', 'Quick zap!', 'Instant!', 'Blink fast!', 'No delay!',
    'Power plant!', 'Generator!', 'Turbine spin!', 'Energy source!', 'Renewable!',
    'Shock therapy!', 'Wake up!', 'Jolt!', 'Buzz buzz!', 'Alive!',
    'Electric slide!', 'Volt dance!', 'Amp groove!', 'Watt moves!', 'Hertz!',
    'Zappy life!', 'Electric soul!', 'Spark spirit!', 'Bolt dream!', 'Zappy forever!'
  ]
};
